### PR TITLE
Basic Commands Design Doc

### PR DESCRIPTION
**Pull request by seendsouza**
Are the commands POSIX compliant and intuitive?

### CODE REVIEW

**Review by jeffrey-dot-li — COMMENTED** [review]
Can you give examples I'm not sure what you mean by data type in specific (like is it a parameter? is it for teams or)

**Review by jeffrey-dot-li — COMMENTED** [review]
Also are we only storing datatypes? We will also be bale to add teams right - theres no mention of that is that just bc you haven't got around to it yet

**Review by jeffrey-dot-li — APPROVED** [review]

**Comment by seendsouza** [comment]
So in this context (will include in my next commit) data type should be a high level data structure that the user will be able to understand. Let's say the user is using the mobile version. When adding a data type, they'll have to give a name to their new data type, and how it stores it so: Shooting Locations: Point; Example: (1,2). "Shooting Locations" is the the name of the data type, and Point is how the user thinks it should be stored (but as you know we'll have to convert from it when storing in sembast).

**Comment by seendsouza** [comment]
Team is the name of a data type that looks like this Team: String (probably should call it Characters or Words to be higher level); Example: "2381C"

**Pull request merged**
